# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.EmailField(max_length=30, unique=True)),
                ('user_pwd', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('batch', models.CharField(max_length=10)),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
