# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_sender', models.CharField(max_length=30)),
                ('chat_reciever', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
