# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_share_post',
            field=models.BooleanField(default=False),
        ),
    ]
