# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20161113_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reason_share',
            new_name='reason_post',
        ),
    ]
